Task3
Dorofei154/bank-app pull request #1
Opened 2022-08-11 13:46 UTC by Dorofei154

2022-08-11 18:05 UTC, ez4navi requested changes

2022-08-13 10:32 UTC, unsafeFunction commented on src/components/checkList/index.tsx
> +  const onCheckAllChange = (e: any) => {
Please use React event hangler types
Ref is here 
https://fettblog.eu/typescript-react/events/

2022-08-13 10:32 UTC, unsafeFunction commented on src/components/currencyConvert/index.tsx
> +    const reg = /^-?\d*(\.\d*)?$/;
Those regexp should be in const

2022-08-13 10:33 UTC, unsafeFunction commented on src/components/currencyConvert/index.tsx
> +    dispatch(setCurrency1(value));
Bad naming
Don't use number for naming
setCurrency1... etc

2022-08-13 10:34 UTC, unsafeFunction commented on src/components/currencyConvert/index.tsx
> +    dispatch(setAmountCurrency2(data * convert.exchange));
The same naming

2022-08-13 10:35 UTC, unsafeFunction commented on src/components/currencyDinamic/index.tsx
> +} from "../../store/slices/currencySlice";
Please read about absolute imports

2022-08-13 10:35 UTC, unsafeFunction commented on src/components/currencyDinamic/index.tsx
> +  wrapperCol: {
Move this const files  to the currencyDynamic.const.ts

2022-08-13 10:36 UTC, unsafeFunction commented on src/components/currencyDinamic/index.tsx
> +        `https://www.nbrb.by/API/ExRates/Rates/Dynamics/${currency.currentCurrency.code}?startDate=${date.rangeDate[0]}&endDate=${date.rangeDate[1]}`
Better to store API Link in .env file

2022-08-13 10:36 UTC, unsafeFunction commented on src/components/currentDay/index.tsx
> +      title: "Abbreviation",
To const in this component
currentDay.const.ts

2022-08-13 10:37 UTC, unsafeFunction commented on src/store/slices/currencyConvertSlice.ts
> +  setCurrencyOnToday,
refactor all naming  with numbers

2022-08-13 10:38 UTC, unsafeFunction commented on src/components/currencyConvert/index.tsx
> +        options={convert.currencyList?.map((item: any) => ({
You can map all outside the render

2022-08-13 10:38 UTC, unsafeFunction commented on src/components/currencyConvert/index.tsx
> +        options={convert.currencyList?.map((item: any) => ({
And use variable in render with mapped list

2022-08-13 10:40 UTC, unsafeFunction commented on src/components/checkList/index.tsx
> +  const { checkedList, defaultCheckedList, checkedAll } = useSelector(
Read about shallowEqal
You can pass this function to useSelector to prevent rerenders

https://react-redux.js.org/api/hooks - ref

2022-08-13 10:41 UTC, unsafeFunction commented on src/components/checkList/index.tsx
> +      {" "}
extra

2022-08-15 06:56 UTC, closed without merging